"""empty message

Revision ID: 79356cc12577
Revises: 2064d28a8ee7
Create Date: 2024-01-15 21:12:07.222473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79356cc12577'
down_revision = '2064d28a8ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('create_time', sa.String(), nullable=True),
    sa.Column('last_login_time', sa.String(), nullable=True),
    sa.Column('jwt_access_token', sa.String(), nullable=True),
    sa.Column('jwt_refresh_token', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('erd')
    # ### end Alembic commands ###
